openapi: 3.0.2
info:
  title: Session Service - Hollow Cube
  description: >-
    TODO BLAH BLAH BLAH WRITE SOME DESCRIPTION HERE
  version: 1.0.0
  x-base-path: "/internal"
externalDocs:
  description: Find out more about Hollow Cube and Map Maker
  url: 'https://docs.hollowcube.net'
servers:
  - url: http://127.0.0.1:9124/internal/v1
paths:
  /session/{playerId}:
    post:
      operationId: createSession
      summary: Create a new session
      parameters:
        - name: playerId
          in: path
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username: { type: string }
                ip: { type: string }
      responses:
        '201':
          x-type: success
          description: Session successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerData'
        '400':
          description: Session already exists
        '401':
          description: Unauthorized
    delete:
      operationId: deleteSession
      summary: Delete a session
      parameters:
        - name: playerId
          in: path
      responses:
        '200':
          x-type: empty
          description: Session deleted

components:
  schemas:
    PlayerData:
      description: This is the v1 object from the player service
      type: object
      additionalProperties: true
