openapi: 3.0.2
info:
  title: Map Service Public API
  version: "1"
paths:
  /terraform/session/{playerId}:
    get:
      operationId: getPlayerSession
      summary: Fetch a player session by the player ID
      description: long description TODO
      parameters:
        - name: playerId
          in: path
      responses:
        '200':
          x-type: success
          description: The raw player session data
          content:
            application/vnd.terraform.player_session:
              schema:
                type: string
                format: binary
        '404':
          x-type: empty
          description: No player data saved
  /terraform/session/{playerId}/{worldId}:
    get:
      operationId: getLocalSession
      summary: Fetch a local session by the player ID and world ID
      description: long description TODO
      parameters:
        - name: playerId
          in: path
        - name: worldId
          in: path
      responses:
        '200':
          x-type: success
          description: The raw local session data
          content:
            application/vnd.terraform.local_session:
              schema:
                type: string
                format: binary
        '404':
          x-type: empty
          description: No local session data saved

components:
  schemas: {}
